### ISSUE TITLE
Vscode xmake 插件无法启动

### ISSUE THREAD

**Issue by RiversJin** [xmake-io/xmake-vscode#219]
### Xmake 版本

xmake v2.7.9+20230515

### 操作系统版本和架构

MacOS 13.3 Intel

### 描述问题

Visual Studio Code 1.81.1 (Universal)
使用 XMake vscode 插件, 版本v2.1.9, 插件不能启动, 输出提示:
![image](https://github.com/xmake-io/xmake-vscode/assets/11208747/3404d4b3-1fde-420b-b0fd-6ce4a72899e6)

### 期待的结果

使其可以正常工作即可

### 工程配置

```
target("demo")
    add_files("src/*.cpp")
    set_kind("binary")
```

### 附加信息和错误日志

```
2023-08-30 14:18:05.099 [info] ExtensionService#_doActivateExtension tboox.xmake-vscode, startup: false, activationEvent: 'onLanguage:xmake'
2023-08-30 14:18:05.202 [error] Activating extension tboox.xmake-vscode failed due to an error:
2023-08-30 14:18:05.202 [error] TypeError: The argument 'file' cannot be empty. Received ''
	at new NodeError (node:internal/errors:387:5)
	at normalizeSpawnArguments (node:child_process:530:11)
	at Object.spawn (node:child_process:745:13)
	at execv (/Users/rivers/.vscode/extensions/tboox.xmake-vscode-2.1.9/out/src/process.js:80:23)
	at Object.runv (/Users/rivers/.vscode/extensions/tboox.xmake-vscode-2.1.9/out/src/process.js:72:12)
	at XMake.<anonymous> (/Users/rivers/.vscode/extensions/tboox.xmake-vscode-2.1.9/out/src/xmake.js:370:37)
	at Generator.next (<anonymous>)
	at /Users/rivers/.vscode/extensions/tboox.xmake-vscode-2.1.9/out/src/xmake.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/rivers/.vscode/extensions/tboox.xmake-vscode-2.1.9/out/src/xmake.js:4:12)
	at XMake.start (/Users/rivers/.vscode/extensions/tboox.xmake-vscode-2.1.9/out/src/xmake.js:359:16)
	at /Users/rivers/.vscode/extensions/tboox.xmake-vscode-2.1.9/out/src/extension.js:63:21
	at Generator.next (<anonymous>)
	at /Users/rivers/.vscode/extensions/tboox.xmake-vscode-2.1.9/out/src/extension.js:8:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/rivers/.vscode/extensions/tboox.xmake-vscode-2.1.9/out/src/extension.js:4:12)
	at activate (/Users/rivers/.vscode/extensions/tboox.xmake-vscode-2.1.9/out/src/extension.js:19:12)
	at Dn.eb (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:13102)
	at Dn.db (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:12816)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:116:10913
	at async p.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:6206)
	at async p.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:6169)
	at async p.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:102:5626)
```

**Comment by waruqi** [comment]
这边可以，你可以拉下插件源码调下

**Comment by RiversJin** [comment]
好的, 我试试
