### ISSUE TITLE
xmake.lua文件无法自动补全

### ISSUE THREAD

**Issue by eddylin83** [xmake-io/xmake-vscode#272]
### Xmake 版本

xmake v2.8.6+HEAD.211710b

### 操作系统版本和架构

Ubuntu 22.04.4 LTS

### 描述问题

在xmake.lua文件中无法自动补全。试过降级到2.3.5，功能正常。

### 期待的结果

xmake.lua文件自动补全

### 工程配置

target("lnx_test")
    set_kind("binary")
    add_files("src/*.c")

### 附加信息和错误日志

vscode的output窗口显示如下信息：
```sh
2024-08-09 14:57:49.737 [error] SyntaxError: Unexpected token 'e', "error: can"... is not valid JSON
	at JSON.parse (<anonymous>)
	at /home/lzb/.vscode-server/extensions/tboox.xmake-vscode-2.3.7/out/src/completion.js:35:43
	at Generator.next (<anonymous>)
	at fulfilled (/home/lzb/.vscode-server/extensions/tboox.xmake-vscode-2.3.7/out/src/completion.js:5:58)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by waruqi** [comment]
版本太低，用 2.9.4

**Comment by eddylin83** [comment]
好的，update xmake之后可以了。
